[package]
name = "udbserver"
version = "0.1.0"
authors = ["Bet4 <0xbet4@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gdbstub = { git = "https://github.com/bet4it/gdbstub", branch = "dyn_regid" }
unicorn-engine = { git = "https://github.com/unicorn-engine/unicorn", branch = "dev", features = ["use_system_unicorn"] }
